### ISSUE TITLE
iOS 8 - ExpandTableCellDemo expend two cell

### ISSUE THREAD

**Issue by Yita55** [quantumarun/Demos#1]
I am trying to run ExpandTableCellDemo on multi-device.
When I run it on iOS9, iOS10 device. All function is OK.
But when I run is on iOS8 device, when I click first cell, it will expend two cell.

Would you tell me how to fix it ? Thanks!

BR,
Yita.

**Comment by quantumarun** [comment]
Strange but yes i too saw it on iOS8. Let me resolve this and update the repo.

**Comment by quantumarun** [comment]
Fixed the issue. Test and Confirm.

**Comment by Yita55** [comment]
Cool!
Why add two line for iOS 8?

expandTableView.estimatedRowHeight = 40
expandTableView.rowHeight = UITableViewAutomaticDimension
